### PR TITLE
Return ordered JSON output

### PR DESCRIPTION
**Pull request by omus**
Useful for when you pull down a IAM policy, modify the contents, then replace it.

### CODE REVIEW

**Comment by samoconnor** [comment]
This is long overdue: https://github.com/JuliaLang/julia/pull/10116

**Comment by samoconnor** [comment]
Would you mind pasting some example code that I can eventually turn into a test case?
One of the use-cases I have in mind for [`LazyJSON.jl`](https://github.com/samoconnor/LazyJSON.jl) is small modifications to large JSON texts. I'm thinking of something like `merge(::LazyJSON.Value, ::Dict)` where a large JSON text can be patched by a `Dict` containing only the changed values. With the lazy parser it should be easy to splice the changes in without having to parse and re-format the bulk of the data.

**Comment by s2maki** [comment]
This is an annoying breaking change.  It would be nice if this were an option, or only enabled in places where it made the most sense.  Is there a way to turn it off on a case-by-case basis?

**Comment by samoconnor** [comment]
That's an oversight on my part.
I've just committed a change that makes OrderedDict an opt-in option via `:ordered_json_dict = true`.

**Comment by s2maki** [comment]
Awesome, thanks!  Will try it out first thing in the morning.

**Pull request merged**
