### PR TITLE
Use testsets and fix ecode UndefVarError

### PR DESCRIPTION
**Pull request by iamed2**
1. Changed `ecode(e)` to `e.code`
2. Made the sections into testsets. This fixed an error that was occurring around the try-catch blocks and also makes failure output nicer

I'll probably base upcoming PRs off of this one for ease of testing.

### CODE REVIEW

**Comment by omus** [comment]
I recommend using separate commits when adding indentation like with adding `@testset`s

**Comment by aviks** [comment]
Hi @samoconnor any thoughts on this and subsequent PRs?

**Comment by tanmaykm** [comment]
This passes tests for me locally. I can merge this in a bit (and a few subsequent PRs that pass tests), unless there are any objections. @samoconnor

**Comment by iamed2** [comment]
@tanmaykm I expect the combination of this and #21 to pass tests on at least one Travis platform

Thank you so much for getting involved!

**Comment by tanmaykm** [comment]
Yes, #21 passes too. Will also test the others.
Thanks for the PRs!

**Comment by samoconnor** [comment]
Hi @iamed2,
`ecode` should work. It comes from here: https://github.com/samoconnor/Retry.jl/blob/master/src/Retry.jl#L8
What error did you get?

**Pull request merged**
