### PR TITLE
Add a CloudFormation template for public AWS CI

### PR DESCRIPTION
**Pull request by ararslan**
Also add documentation on the process for setting this up.

### CODE REVIEW

**Comment by omus** [comment]
@iamed2 can you verify that I setup travis correctly? https://travis-ci.org/JuliaCloud/AWSCore.jl/settings

**Comment by iamed2** [comment]
Looks like pull requests neither use the fork's secret environment variables nor the source's secret environment variables. There used to be a setting to change that but looks like they removed that.

**Comment by ararslan** [comment]
Why did CI work on my pull request to our fork then?

**Comment by iamed2** [comment]
You didn't make that PR from a separate fork

**Comment by ararslan** [comment]
Ohh you're right.

**Comment by iamed2** [comment]
Looks like we either have to:

1. not work from forks
2. un-secret the environment variables

**Comment by ararslan** [comment]
Weird, probably overkill idea: Use [bors](https://github.com/apps/bors) for running tests. IIRC it puts changes into a branch on the repo and tests from there rather than using the branch directly from the fork. It has some incredibly annoying behaviors but at least it can do that.

**Comment by iamed2** [comment]
I support the `bors` solution.

**Comment by ararslan** [comment]
Okay, well I told Travis when it should build, but it doesn't seem to care.

**Comment by iamed2** [comment]
Pull requests build on `master`, you have to disable that or disable building pull requests in the Travis settings.

**Comment by iamed2** [comment]
https://bors.tech/documentation/getting-started/

**Comment by omus** [comment]
bors try

**Comment by ararslan** [comment]
Nice, looks like bors is working! Can someone with access make the necessary changes to the Travis settings?

**Comment by omus** [comment]
Travis modified. Here we go!

**Comment by omus** [comment]
bors try

**Comment by iamed2** [comment]
What is the second `bors try` checking?

**Comment by omus** [comment]
I disabled the automatic PR building in the Travis CI settings. I also removed `AWS_DEFAULT_REGION`.  If this passes I'm happy with this. There will be some work to cleanup the CI setup in this repo though.

**Pull request merged**
