### PR TITLE
Added capabilities to use different S3 backed storages other than AWS'

### PR DESCRIPTION
**Pull request by mattBrzezinski**
I do not have permissions to push on @meggart fork, to get this into `master` in time for them I've just created another CR so that I can push it through.

Same changes as: #82

### CODE REVIEW

**Comment by meggart** [comment]
This is great, thanks. Would you mind to tag a new release, so that my downstream packages can depend on this change?

**Comment by mattBrzezinski** [comment]
Not sure if you've recently updated, but the release went through yesterday.

https://github.com/JuliaRegistries/General/pull/6258

**Comment by meggart** [comment]
Yes, I have seen it yesterday. Thanks again.

**Pull request merged**
