### PR TITLE
Added Julia1.0 in Compat section of Project.toml

### PR DESCRIPTION
**Pull request by mattBrzezinski**

### CODE REVIEW

**Comment by mattBrzezinski** [comment]
> Did you manually add this? It seems to be in a weird spot

Yes, I manually did. I figured it's the proper spot since it fits alphabetically within the tags `[compat], [deps], [extras], [target]`.

**Comment by omus** [comment]
> Yes, I manually did. I figured it's the proper spot since it fits alphabetically within the tags [compat], [deps], [extras], [target].

Completely reasonable. Unfortunately the package manager has it's own ideas about where things should go. If you run resolve I bet it'll move it.

**Comment by mattBrzezinski** [comment]
> > Yes, I manually did. I figured it's the proper spot since it fits alphabetically within the tags [compat], [deps], [extras], [target].
> 
> Completely reasonable. Unfortunately the package manager has it's own ideas about where things should go. If you run resolve I bet it'll move it.

It did, force pushed under the same commit message. I'll let `bors` finish running and have it merge in. I assume that the placement of the `compat` section doesn't affect anything? (No need to re-run the CI for just moving the compat placement)

**Pull request merged**
