### PR TITLE
Use delay when retrying throttled requests

### PR DESCRIPTION
**Pull request by morris25**
Uses exponential backoff to avoid more throttling errors.

### CODE REVIEW

**Comment by iamed2** [comment]
Not all of those are actually throttling errors. Check cases where `cause = "throttling"` for which ones are.

**Comment by morris25** [comment]
Apart from the crc32body exception, would it be reasonable to apply the delay to the other errors in this block as well? "PriorRequestNotComplete" seems like it might benefit but I'm not sure about the timeout errors.

**Comment by iamed2** [comment]
"PriorRequestNotComplete" should be with throttling.

"RequestTimeout" and "RequestTimeoutException" should be separate from throttling I think.

I trust https://github.com/jasdel/aws-sdk-go/blob/master/aws/request/retryer.go to have appropriately classified those.

**Comment by iamed2** [comment]
In general, the Go AWS SDK is a pretty good reference for good practice IMO as it's comprehensive and well-used but also very clearly written (especially when compared to the inscrutable boto/botocore).

**Pull request merged**
