### PR TITLE
Delimiters should be escaped during date parsing

### PR DESCRIPTION
**Pull request by rofinn**
Also, using the dateformat string macro should speed up parsing.

### CODE REVIEW

**Comment by samoconnor** [comment]
Hi @rofinn, thanks for the PR. Can you explain the motivation for this change? does the existing code fail in some case? is it a deprecation warning fix? just good practice?

**Comment by samoconnor** [comment]
From my reading of this https://docs.julialang.org/en/latest/stdlib/Dates/#Dates.DateFormat there is no need to escape `T` or `Z` ?

**Comment by rofinn** [comment]
So, it only fails if TimeZones.jl is loaded as it use `Z`. You are correct that escaping `T` isn't necessary now, but if you're intending for it to be used as a delimiter it seemed like a good safety precaution.

https://github.com/JuliaTime/TimeZones.jl/commit/2b032da7cc96fc479600d7f480fb1af8a41d158f

**Comment by samoconnor** [comment]
Makes sense. thanks!

**Comment by rofinn** [comment]
Awesome, thanks.

**Pull request merged**
