### PR TITLE
Adds testing on ECS

### PR DESCRIPTION
**Pull request by morris25**
A cleaned up version of ECS testing from #71.
In response to #66.

### CODE REVIEW

**Comment by morris25** [comment]
Tests will fail until the stack is launched on the public CI.

**Comment by iamed2** [comment]
Looks good, let's try it out

**Comment by morris25** [comment]
bors try

**Comment by morris25** [comment]
Apparently `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` doesn't get set unless a JobRole is included.

**Comment by morris25** [comment]
bors try

**Pull request merged**
