### PR TITLE
Add Project.toml and .gitignore files

### PR DESCRIPTION
**Pull request by ararslan**
Tests pass when combined with https://github.com/invenia/AWSCore.jl/pull/1 and run with `--project=.`

### CODE REVIEW

**Comment by omus** [comment]
Should be rebased so that `bors` can run

**Comment by ararslan** [comment]
bors try

**Comment by ararslan** [comment]
rip

**Comment by iamed2** [comment]
bors try

**Comment by omus** [comment]
@ararslan I've granted to access to `bors try` here

**Pull request merged**
